apiVersion: v1
data:
  master-schema.json: |-
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "type": "object",
      "properties": {
        "paramA1": {
          "type": "string"
        }
      },
      "required": [
        "paramA1"
      ]
    }
  workflowA-schema.json: |-
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "type": "object",
      "properties": {
        "paramA1": {
          "type": "string"
        }
      },
      "required": [
        "paramA1"
      ]
    }
  workflowB-schema.json: |-
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "type": "object",
      "properties": {
        "paramB1": {
          "type": "string"
        }
      },
      "required": [
        "paramB1"
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 01-master-resources-schemas
  namespace: subflows-example
